### ISSUE TITLE
Adding DropCAltAndLiga to build.py

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#44]
@chase brilliant work on updating the script. I'll try re-adding the calt today. Is this correct for the build.py script: 
```
# no calt
option('nocalt', 'Turn off contextual alternates', DropCAltAndLiga())
```

**Comment by chase** [comment]
Should be, never actually gave it a try, haha.

**Comment by larsenwork** [comment]
I just tried it and didn't seem to work: 
```
for file in ./Source/Monoid*.sfdir; do . Scripts/parallel_build.sh $file; done
Total Nodes: 4
Current Node: 0
Traceback (most recent call last):
  File "./Scripts/build.py", line 50, in <module>
    option('nocalt', 'Turn off contextual alternates', DropCAltAndLiga())
  File "/data/Scripts/fontbuilder.py", line 167, in DropCAltAndLiga
    return swap_op
NameError: global name 'swap_op' is not defined
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
Total Nodes: 4
Current Node: 0
Traceback (most recent call last):
  File "./Scripts/build.py", line 50, in <module>
    option('nocalt', 'Turn off contextual alternates', DropCAltAndLiga())
  File "/data/Scripts/fontbuilder.py", line 167, in DropCAltAndLiga
    return swap_op
NameError: global name 'swap_op' is not defined
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
Total Nodes: 4
Current Node: 0
Traceback (most recent call last):
  File "./Scripts/build.py", line 50, in <module>
    option('nocalt', 'Turn off contextual alternates', DropCAltAndLiga())
  File "/data/Scripts/fontbuilder.py", line 167, in DropCAltAndLiga
    return swap_op
NameError: global name 'swap_op' is not defined
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
Total Nodes: 4
Current Node: 0
Traceback (most recent call last):
  File "./Scripts/build.py", line 50, in <module>
    option('nocalt', 'Turn off contextual alternates', DropCAltAndLiga())
  File "/data/Scripts/fontbuilder.py", line 167, in DropCAltAndLiga
    return swap_op
NameError: global name 'swap_op' is not defined
lxc-start: The container failed to start.

lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options. for file in ./Source/Monoid*.sfdir; do . Scripts/parallel_build.sh $file; done returned exit code 1
```
any ideas?

**Comment by chase** [comment]
Yep, forgot to change `swap_op` on the return to the name it needed.

**Comment by chase** [comment]
Should work now. Give it another try.

**Comment by larsenwork** [comment]
Thanks, will do - with `DropCAltAndLiga()` enabled?

**Comment by chase** [comment]
Right. Worst case it doesn't work, then you have remove it and it runs another build.

**Comment by larsenwork** [comment]
Ok, running now :)

**Comment by chase** [comment]
Looks like it is working too. Considering the only bug was a small typo, I'm pretty happy, haha.

**Comment by larsenwork** [comment]
yep, looks perfect
