### ISSUE TITLE
SwapLookup Fontbuilder

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/monoid#94]
```
Traceback (most recent call last):
  File "./Scripts/build.py", line 46, in <module>
    option('Squeeze', 'Squeezed capitals with diacritics', SwapLookup("ss14"))
  File "/data/Scripts/fontbuilder.py", line 158, in SwapLookup
    return swap_op
NameError: global name 'swap_op' is not defined
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
for file in ./Source/Monoid*.sfdir; do . Scripts/parallel_build.sh $file; done returned exit code 1
```
@chase ? :bowtie:
https://github.com/larsenwork/monoid/blob/master/Scripts/build.py#L46

**Comment by chase** [comment]
Could have sworn I fixed this already, haha.

**Comment by larsenwork** [comment]
https://gist.github.com/larsenwork/a3398e553de1d547f8b8 almost... :)

**Comment by chase** [comment]
This is going to require some more digging, for now we should remove line 46. https://github.com/larsenwork/monoid/blob/master/Scripts/build.py#L46

**Comment by larsenwork** [comment]
ok, I'll just comment it out

**Comment by larsenwork** [comment]
cancelled the rebuild - building 0.55 instead :)
